defaults:
  - _self_
  - optional tuner_config: Inception/${stages/preprocess}

classifier_name: Inception
tuner_config:
  hyperparam_tuning:
    backbone:
      depth:
        sampling_name: choice
        config:
          categories:
            - 3
            - 6
            - 9
            - 12
      kernel_size:
        sampling_name: choice
        config:
          categories:
            - 8
            - 16
            - 32
            - 40
            - 64
      num_kernels:
        sampling_name: choice
        config:
          categories:
            - 4
            - 8
            - 16
            - 32
            - 64
            - 128
      bottleneck_size:
        sampling_name: choice
        config:
          categories:
            - 64
            - 32
            - 16
            - 8
            - 4
            - 2
    training:
      per_device_train_batch_size:
        sampling_name: choice
        config:
          categories:
            - 32
            - 16
            - 64
            - 128
  hyperparam_fixed:
    time_limit: ${global.tune_time_limit}
    backbone:
      use_bottleneck: true
    training:
      learning_rate: 0.001
      num_train_epochs: ${global.max_tune_epochs}
ray_config:
  resources_per_trial:
    gpu: 1