defaults:
  - _self_
  - optional tuner_config: VRADA/${stages/preprocess}

classifier_name: VRADA
tuner_config:
  hyperparam_tuning:
    backbone:
      VRNN_z_dim:
        sampling_name: choice
        config:
          categories:
            - 100
            - 200
      VRNN_h_dim:
        sampling_name: choice
        config:
          categories:
            - 100
            - 200
    classifier:
      R_loss_w:
        sampling_name: loguniform
        config:
          upper: 0.001
          lower: 0.0001
  hyperparam_fixed:
    max_epochs_lr_scheduler: ${global.dann.max_epochs_lr_scheduler}
    time_limit: ${global.tune_time_limit}
    training:
      learning_rate: 0.0003
      lr_scheduler_type: constant
      per_device_train_batch_size: 32
      num_train_epochs: ${global.max_tune_epochs}
ray_config:
  resources_per_trial:
    gpu: 1
