tune:
  random_seed: 1
  search_method_names:
    - None
  no_tune: no_tune
train:
  config:
    backbone:
      n_input_channels: 1
      n_mid_channels: 32
      kernel_size: 8
      dropout: 0.2
      n_out_channels: 4
      avgpool_to: 32
    classifier:
      num_labels: 2
      mix_ratio: 0.78
      temporal_shift: 15
      beta1: 0.95
    training:
      learning_rate: 0.003
      per_device_train_batch_size: 32
      per_device_eval_batch_size: 32
      num_train_epochs: 20
      save_strategy: steps
      evaluation_strategy: steps
      logging_strategy: epoch
      lr_scheduler_type: constant
      weight_decay: 0.0001
    do_checkpoint: true
    device: cuda
  tune_config:
    search_method_names:
      - None
    train_tune_option: train_configs_only
predict:
  load_model:
    checkpoint: best
    metric_key: accuracy
    best: maximum