classifier:
  C: 1
  kernel: rbf
  degree: 3
  gamma: scale
  coef0: 0.0
  shrinking: True
  probability: True
  tol: 0.001
  cache_size: 200
  class_weight: null
  verbose: False
  max_iter: -1
  decision_function_shape: ovr
  break_ties: False
  random_state: 42