defaults:
  - _self_
  - optional config: MLPClassifier/${stages/preprocess}

classifier_name: MLPClassifier
config:
  do_checkpoint: true
  time_limit: ${global.train_time_limit}
  backbone:
    n_hidden: 8
    out_dim: 16
  training:
    learning_rate: 0.001
    num_train_epochs: ${global.max_train_epochs}
tune_config:
  search_method_name: None
  train_tune_option: train_configs_only
no_shuffle_split_config:
  n_splits: 1
  test_size: 0.1